### PR TITLE
google auth

### PR DESCRIPTION
**Pull request by GeoffreyEmery**
Updated Firebase creation section to include the google auth provider in order to sign in on a new project. Also cleaned up a the replacement token language a bit.

### CODE REVIEW

**Comment by GeoffreyEmery** [comment]
I Signed it.

**Comment by GeoffreyEmery** [comment]
Also I just booted this up a new computer and it didn't have bower on it so the npm run serve broke on the bower dependency.  I just did a quick  $ npm install -g bower but for some reason it still broke so i did the bower install direct and then removed it from the serve in the package.json. Seems like something may be a bit funky in your package file.

**Comment by hackidozone** [comment]
hi, why i always get google sign in failed. anybody can help me?

**Comment by nicolasgarnier** [comment]
@GeoffreyEmery  thanks for this and sorry the delay! I'll merge it now :)
Are you sure you ran `npm install` before trying to run the app? bower should be installed as a local dev dependency by npm...
@hackidozone Can you please open an issue for this (use the **Issues** tab) since this is a Pull Request. Also please include as much details as you can about your issue including error messages from the JS console, reproduction steps, maybe deploy your app (using `firebase deploy`).

**Comment by GeoffreyEmery** [comment]
@hackidozone   google sign in failed is because you need to update the  Firebase project to include the google auth provider in order to sign in on a new project. If the pull went through it should be int he readme now..

**Pull request merged**
